name: Build and Release smail

on:
  push:
    tags:
      - "v*"

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Poetry
        run: pip install poetry

      - name: Install project dependencies
        working-directory: ./smail
        run: poetry install --no-root

      - name: Build wheel and source distribution
        working-directory: ./smail
        run: poetry build

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          # nahraje všechny balíčky z dist/
          files: |
            smail/dist/*.whl
            smail/dist/*.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
